var fs = require ("fs");
var path = require ("path");

// let the routes generated by koa-router and koa-resource-router to be in the same JSON format :-D
function unify(router) {

  var point = {
    name : "",
    routes : []
  }
  
  if (router.name) {
    point.name = router.name;

    router.routes.forEach(function(route){
      route.regexp = route.regexp.toString();
      point.routes.push(route);
    });

  }
  else {
    router.routes.forEach(function(route){
      
      point.name = route.name;

      var i = route.methods.length;

      while (i--) {
        point.routes.push({
          url : route.path,
          method : route.methods[i],
          regexp : route.regexp.toString(),
          params : route.params
        });
      }
    });
  }
  return point;
}

module.exports = function (options){

  var endpoints = fs.readdirSync(__dirname);
  var routes = [];
  var stack = [];

  endpoints.forEach (function (endpoint){
    if (!path.extname (endpoint)) {
      var router = require (path.join(__dirname, endpoint));
      routes.push (unify(router(options)));
      stack.push (router(options).middleware());
    }
  });

  return {
    stack : stack,
    routes : routes
  };
}